---

- name: "install chezmoi"
  become: true
  shell: |
    sh -c "$(curl -fsLS get.chezmoi.io)" -- -b /usr/local/bin
  args:
    executable: /bin/bash

- name: "chezmoi init"
  ansible.builtin.command:
    cmd: chezmoi init --apply {{ dotfiles.repo }} --branch {{ dotfiles.branch }}
  args:
    creates: "{{ ansible_user_dir }}/.local/share/chezmoi"

- name: "chezmoi update"
  ansible.builtin.command: chezmoi update --force
  register: chezmoi_update
  changed_when: '"Updating" in chezmoi_update.stderr'
