set -s repeat-time 1000

# Terminal colors
set -g default-terminal "tmux-256color"
set-option -sa terminal-overrides ",xterm-256color:RGB"

# Enable mouse mode
set -g mouse on

# Enable clipboard
set -g set-clipboard on

# Set scrollback size
set -g history-limit 15000

# set focus events on for nvim
set -g focus-events on

# Do not detach when destroying a session
set -g detach-on-destroy off 

# Use vi or emacs-style key bindings in copy mode
set-window-option -g mode-keys vi

# Keybinds
# Set prefix key
unbind C-b
set -g prefix C-space
bind C-Space send-prefix

# Next and prev window navigation
bind -r C-n next-window
bind -r C-p previous-window
bind -r l next-window
bind -r h previous-window

# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set -g renumber-windows on

# Panes
# bind x kill-pane # skip "kill-pane 1? (y/n)" prompt
bind | split-window -h -c "#{pane_current_path}"
# bind v split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
# bind s split-window -v -c "#{pane_current_path}"

# joins the chosen pane horizontally/vertically into your current window.
bind V choose-tree -F '#{E:@custom_choose_tree_format}' -Z 'join-pane -h -s "%%"'
bind S choose-tree -F '#{E:@custom_choose_tree_format}' -Z 'join-pane -v -s "%%"'

# Better resizing
bind -r -T prefix C-j resize-pane -D 2
bind -r -T prefix C-k resize-pane -U 2
bind -r -T prefix C-h resize-pane -L 2
bind -r -T prefix C-l resize-pane -R 2

# Copy mode
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# Load plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'mrjones2014/smart-splits.nvim'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'nhdaly/tmux-better-mouse-mode'

# Plugin options
set -g @resurrect-strategy-nvim 'session'
set -g @continuum-restore 'on'
set -g @scroll-speed-num-lines-per-scroll "1"

# Load custom theme
source-file ~/.config/tmux/palettes/everforest-dark-medium.tmux
source-file ~/.config/tmux/themes/minimal.tmux

run '~/.config/tmux/plugins/tpm/tpm'

