---

apt_packages:
  - bat
  - build-essential
  - curl
  - wget
  - gh
  - htop
  - neofetch
  - tmux
  - tree
  - ripgrep
  - vim

brew:
  taps:
    - homebrew/bundle
    - homebrew/cask
    - homebrew/cask-fonts
    - homebrew/core

  casks:
    - 1password
    - 1password-cli
    - alfred
    - google-chrome
    - hiddenbar
    - karabiner-elements
    - wezterm

  formulae:
    - awscli
    - bat
    - curl
    - ffmpeg
    - fzf
    - gh
    - htop
    - lazygit
    - neofetch
    - koekeishiya/formulae/skhd
    - tmux
    - tree
    - ripgrep
    - wget
    - koekeishiya/formulae/yabai

dotfiles:
  repo: 'https://github.com/alex-bue/dotfiles'
  branch: 'main'

neovim:
  build_from_source: true
  directory: "{{ ansible_user_dir }}/Development/repository/github.com/neovim/neovim"
  build_dependencies:
    - autoconf
    - automake
    - cmake
    - curl
    - doxygen
    - g++
    - gettext
    - libtool
    - libtool-bin
    - ninja-build
    - pkg-config
    - unzip
