---
- hosts: 127.0.0.1
  strategy: linear
  connection: local

  vars_files:
    - config.yaml

  roles:
    - name: packages
      tags: packages

    - name: fonts
      tags: fonts

    - name: dotfiles
      tags: dotfiles

    - name: zsh
      tags: zsh

    - name: neovim
      tags: neovim

    - name: system_defaults
      tags: system_defaults
