---

- name: "install"
  community.general.homebrew:
    name: zsh
  when: ansible_os_family == "Darwin"
  tags: homebrew

- name: "install"
  become: true
  ansible.builtin.apt:
    name: zsh
    state: present
    update_cache: true
  when: ansible_os_family == "Debian"

- block:
  - name: "obtain path to zsh"
    ansible.builtin.command: which zsh
    register: zsh_path
    changed_when: false

  - name: "change default shell to zsh"
    become: true
    ansible.builtin.user:
      name: '{{ ansible_user }}'
      shell: '{{ zsh_path.stdout }}'

  tags: zsh_chsh

# PLUGINS
- name: "create .zsh_plugins directory"
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.zsh_plugins"
    state: directory
    mode: '0755'

# Powerlevel10k
- name: "clone powerlevel10k"
  git:
    repo: 'https://github.com/romkatv/powerlevel10k.git'
    dest: "{{ ansible_user_dir }}/.zsh_plugins/powerlevel10k"
    version: HEAD

# zsh-autosuggestions
- name: "clone zsh-autosuggestions"
  git:
    repo: 'https://github.com/zsh-users/zsh-autosuggestions.git'
    dest: "{{ ansible_user_dir }}/.zsh_plugins/zsh-autosuggestions"
    version: HEAD

# zsh-syntax-highlighting
- name: "clone zsh-syntax-highlighting"
  git:
    repo: 'https://github.com/zsh-users/zsh-syntax-highlighting.git'
    dest: "{{ ansible_user_dir }}/.zsh_plugins/zsh-syntax-highlighting"
    version: HEAD

# fzf
- name: "fetch fzf from github"
  git:
    repo: 'https://github.com/junegunn/fzf.git'
    dest: "{{ ansible_user_dir }}/.zsh_lugins/fzf"
    version: HEAD

- name: "install fzf"
  ansible.builtin.shell:
    cmd: "./install --key-bindings --completion --no-update-rc"
    chdir: "{{ ansible_user_dir }}/.zsh_plugins/fzf"



