#!/bin/zsh

# Export Environment Variable #

# ensure path is correct
export PATH="$HOME/bin:$PATH"
export PATH="$HOME/go/bin:$PATH"
export PATH="$HOME/.cargo/bin:$PATH"
export PATH="$HOME/.local/bin:$PATH"


# editor
export EDITOR="nvim"
export VISUAL="nvim"

# zsh
export HISTSIZE=10000                   # Maximum events for internal history
export SAVEHIST=10000                   # Maximum events in history file
