#!/usr/bin/env sh

# scripting additions (requires system integrity protection to be disabled)
#sudo yabai --load-sa
#yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# global settings
yabai -m config layout                       bsp
yabai -m config window_placement             second_child
yabai -m config window_origin_display        default

### WINDOW SETTINGS
# yabai -m config window_shadow                on
# yabai -m config window_border                on
# yabai -m config window_border_width          3
# yabai -m config active_window_border_color   0xFFECEFF4 # Nord White
# yabai -m config normal_window_border_color   0xFF606060 # For Soft Gray
# yabai -m config insert_feedback_color        0xFF3B4252 # For Muted Blue
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off

# the following window settings require SIP disabled
# yabai -m config window_topmost               off
# yabai -m config window_opacity               off
# yabai -m config window_opacity_duration      0.0
# yabai -m config active_window_opacity        1.0
# yabai -m config normal_window_opacity        0.9

### MOUSE SETTINGS
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off

yabai -m config mouse_modifier               alt
yabai -m config mouse_action1                move # left click + drag
yabai -m config mouse_action2                resize # right click + drag
yabai -m config mouse_drop_action            swap

### Padding and Gaps
yabai -m config top_padding                  8
yabai -m config bottom_padding               8
yabai -m config left_padding                 8
yabai -m config right_padding                8
yabai -m config window_gap                   8

# focus window below the cursor after window closed
yabai -m signal --add event=window_destroyed action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"
yabai -m signal --add event=application_terminated action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"

# apps to not manage (ignore)
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Raycast" manage=off
yabai -m rule --add app="^Alfred Preferences$" manage=off
yabai -m rule --add app="^Karabiner-Elements$" manage=off
yabai -m rule --add app="^Archive Utility$" manage=off
yabai -m rule --add app="^Logi Options$" manage=off
#yabai -m rule --add app="^VMware Fusion$" manage=off
yabai -m rule --add app="^Music$" manage=off

echo "yabai configuration loaded.."
