---

- name: Download WezTerm .deb package for Ubuntu 20.04
  become: true
  get_url:
    url: "https://github.com/wez/wezterm/releases/download/20230712-072601-f4abf8fd/wezterm-20230712-072601-f4abf8fd.Ubuntu20.04.deb"
    dest: "/tmp/wezterm.deb"
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '20.04'

- name: Download WezTerm .deb package for Ubuntu 22.04
  become: true
  get_url:
    url: "https://github.com/wez/wezterm/releases/download/20230712-072601-f4abf8fd/wezterm-20230712-072601-f4abf8fd.Ubuntu22.04.deb"
    dest: "/tmp/wezterm.deb"
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '22.04'

- name: Install WezTerm from .deb package
  become: true
  apt:
    deb: "/tmp/wezterm.deb"
